package jpabook.start;

import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.EntityTransaction;
import javax.persistence.Persistence;
import java.util.List;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class JpaMain {

    private static final String id = "id1";

    public static void main(String[] args) {

        // 엔티티 매니저 팩토리 - 생성
        EntityManagerFactory entityManagerFactory = Persistence.createEntityManagerFactory("jpabook");

        // 엔티티 매니저 - 생성
        EntityManager entityManager = entityManagerFactory.createEntityManager();

        // 트랜잭션 - 획득
        EntityTransaction entityTransaction = entityManager.getTransaction();

        try {
            entityTransaction.begin();
            logic(entityManager);
            entityTransaction.commit();

        } catch (Exception e) {
            e.printStackTrace();
            entityTransaction.rollback();
        } finally {
            entityManager.close();
        }
        entityManagerFactory.close();

    }

    private static void logic(EntityManager entityManager) {
        Member member = new Member();
        member.setId(id);
        member.setUsername("hyunto");
        member.setAge(20);

        // 등록
        entityManager.persist(member);

        // 수정
        member.setAge(30);

        // 한 건 조회
        Member findMember = entityManager.find(Member.class, id);
        System.out.println("findMember=" + findMember.getUsername() + ", age=" + findMember.getAge());

        // 목록 조회
        List<Member> members = entityManager.createQuery("select m from Member m", Member.class).getResultList();
        System.out.println("member.size=" + members.size());

        // 삭제
        entityManager.remove(member);
    }

}
