/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import jpabook.start.JpaMain;
import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test public void testAppHasAGreeting() {
        JpaMain classUnderTest = new JpaMain();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }
}
